### ISSUE TITLE
How to calculate the normal map of the PHSPD dataset?

### ISSUE THREAD

**Issue by Dengzhi-USTC** [JimmyZou/PolarHumanPoseShape#1]
hi, it's my pleasure to enjoy your work.
there a question, what is the gt normal map of the PHSPD when you calculate the error in table1 of paper?

thank you.

**Comment by JimmyZou** [comment]
Hello, we calculate the normal map from three-view depth images, and use these normal maps for training and testing. Though the normal map calculated from depth is a little bit noisy, the tested results seems to be not bad.

Basically, we calculate the normal map according to the following steps: **(updated depth2normal.py)**
(1) we convert each view depth image to the polarization image plane as one view polarization depth image
(2) for each view polarization depth image, we crop the valid the region (non-zero depth)
(3) calculate the normal in the valid region for each view polarization depth image
(4) synthesize three-view normal and smooth the normal map
(5) convert xyz normal to angle normal and save it
